// v13 SHORT (IEEE-ICCA'26, 6-page A4). Every number is read from results.json
// (make_results.py); none is typed by hand. Extended version = v12.

const path = require("path");
const fs = require("fs");
const RES = require(path.join(__dirname, "results.json"));
const M4 = RES.models["gpt-4o-mini"];
const M6 = RES.models["gpt-6-astra"];
const W4 = RES.wording["gpt-4o-mini"];
const W6 = RES.wording["gpt-6-astra"];
const C4 = M4.conditions, C6 = M6.conditions;
const F4 = (RES.followup || {})["gpt-4o-mini"] || {};
const F6 = (RES.followup || {})["gpt-6-astra"] || {};
const FN4 = F4.levels.X3_note_neutral;
const FN6 = F6.levels.X3_note_neutral;
const fpair = (F, a, b) => (F.pairs || []).find(p => p.a === a && p.b === b);

const pc = (x, d = 1) => (x === null || x === undefined || x !== x) ? "n/a" : (x * 100).toFixed(d);
const pp = (x, d = 1) => (x === null || x === undefined) ? "n/a" : ((x * 100 >= 0 ? "+" : "−") + Math.abs(x * 100).toFixed(d));
const ci = (t) => `[${pc(t[0], 0)}–${pc(t[1], 0)}]`;
const pv = (p) => p < 0.0005 ? "<0.001" : p.toFixed(3);
const nm = (x) => x.toFixed(0);
const jci = (t) => `[${(t.youden_ci[0]*100).toFixed(0)},${(t.youden_ci[1]*100).toFixed(0)}]`.replace(/-/g, "−");
const bc = (r) => `${nm(r.a_only)}/${nm(r.b_only)}`;
const peq = (p) => p < 0.0005 ? "p < 0.001" : `p = ${p.toFixed(3)}`;
const rng = (C, key, conds) => { const v = conds.map(c => C[c][key]); return `${pc(Math.min(...v))}–${pc(Math.max(...v))}`; };
const relred = (a, b) => pc((a - b) / a, 0);
const SB = ["B1_structured", "B1N_structured_norm", "B2_sanitized", "B3_constrained"];

const REPO = "https://github.com/chpark0714/pag-alert-triage (release v1.0)";  // filled at release
const TITLE = "Provenance Marking and Information Exclusion in LLM-Augmented Alert Triage: Security Effects and Operational Costs";

const authorsBlock = [
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [R(TITLE, { size: 44 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [R("Angelin Lipika Edwin Jose Jebaslin Vijila and Chol Hyun Park", { size: 22 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [R("Department of Computer Science", { size: 20, italics: true })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [R("University of the Ozarks, Clarksville, AR, USA", { size: 20, italics: true })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 300 }, children: [R("{alipi418, cpark}@ozarks.edu", { size: 20 })] }),
];

const abstractPara = new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 100 },
  children: [
    R("Abstract—", { size: 18, bold: true, italics: true }),
    R(`Security operations centers increasingly route intrusion-detection alerts through large language models, and much of an alert's text is written by the party under investigation. We evaluate two responses to the resulting injection channel — provenance-aware rendering, which labels attacker-writable fields and relocates them to a referenced appendix, and an asymmetric downgrade gate, which re-verifies benign verdicts from sensor-generated fields only — against baselines with explicit reference conditions, on alerts in three strata, on two models. The injected miss rate on malicious alerts and the over-escalation rate on benign alerts are co-primary, with exact McNemar tests paired on the same alert. On gpt-4o-mini, relative to the naive baseline, the rendering cuts injected misses from ${pc(C4.B0_naive.injected_miss)}% to ${pc(C4.P1_pag_render.injected_miss)}% and raises over-escalation from ${pc(C4.B0_naive.oer)}% to ${pc(C4.P1_pag_render.oer)}% (from ${pc(C4.B1_structured.injected_miss)}% and ${pc(C4.B1_structured.oer)}% for the structured primary baseline); clean-task Youden's J falls from ${pp(C4.B0_naive.youden_j)} to ${pp(C4.P1_pag_render.youden_j)} (95% interval ${jci(C4.P1_pag_render)}). The gate reaches zero misses by escalating every alert. No advantage of appendix relocation over inline labeling was demonstrated. On a frontier model the corpus flips no verdict, yet the same prompts raise over-escalation from ${pc(C6.B0_naive.oer)}% to ${pc(C6.P1_pag_render.oer)}–${pc(C6.P2_pag_full.oer)}%. A post hoc neutral rewording of the same layout removes most of the cost on the small model but not on the frontier model. On this benchmark the defenses moved the operating point toward escalation; an improvement in discrimination could not be shown, and the cost appeared on both models while attack success from this corpus was observed on one.`, { size: 18, bold: true }),
  ],
});

const indexTerms = new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 160 },
  children: [R("Index Terms—", { size: 18, bold: true, italics: true }),
             R("prompt injection, large language models, security operations center, alert triage, provenance, alert fatigue, evaluation methodology", { size: 18, bold: true })],
});

const intro = [
  H1("Introduction"),
  body(`Large language models are deployed as first-line analysts in security operations: tooling presents the model with an intrusion-detection alert and asks whether to escalate, monitor, or close. The motivation is volume. Practitioners describe false-positive rates as high as 99% and identify volume, not analytic difficulty, as the dominant source of burnout [14], [13].`, { noIndent: true }),
  body(`These pipelines contain a structural hazard. Alerts are not written by the defender; much of their content originates in traffic the attacker generated — the User-Agent header, the request path, attempted usernames, the preserved log line. Serializing such an alert into a prompt gives the attacker a channel to the analyst's reasoning that requires no privilege beyond sending traffic to a public service: *indirect prompt injection* [1]. Pandey and Bhujang [11] and Landauer et al. [12] establish exploitability in this setting (Section II); both find imperative overrides ineffective, and what survives resembles context — a ticket number, a named security lead, an approved window.`),
  body(`We take up two questions these studies leave open. *Which component of a mitigation is responsible for its effect?* Existing defenses bundle delimiters, warnings, filtering, templating, and normalization, and the literature does not say which part did the work. *What does the mitigation cost?* A defense that reduces attack success by making the model suspicious of all attacker-written text will also escalate benign alerts, reproducing the fatigue such systems were adopted to relieve. Prior work includes benign cases as a guard against label-everything defenses [11] but does not report the benign false-positive rate as a result. Here it is co-primary, and it turns out to be decisive.`),
  body(`We study two interventions and state what each does and does not provide. *Provenance-aware rendering* assigns trust tiers by schema and relocates attacker-writable values to a referenced appendix; it is prompt-level marking in the sense of spotlighting [6] and offers no information-flow guarantee. *An asymmetric downgrade gate* re-verifies benign verdicts in a second call that receives trusted fields only; it excludes attacker text, but is triggered by a first-stage verdict the attacker may have influenced and cannot recover what the exclusion removed.`),
  body(`The result is not the one the design was built to confirm. On gpt-4o-mini the rendering cuts the injected miss rate from ${pc(C4.B1_structured.injected_miss)}% under the structured primary baseline (${pc(C4.B0_naive.injected_miss)}% unprotected) to ${pc(C4.P1_pag_render.injected_miss)}%, significantly, but escalates ${pc(C4.P1_pag_render.oer)}% of benign alerts against ${pc(C4.B1_structured.oer)}% (${pc(C4.B0_naive.oer)}% unprotected), and its attack-free Youden's J is ${pp(C4.P1_pag_render.youden_j)} with an interval ${jci(C4.P1_pag_render)} that includes zero. The gate reaches zero misses by escalating every alert. On a frontier model the corpus does nothing, and the same prompts still raise over-escalation by ${pp(C6.P1_pag_render.oer - C6.B0_naive.oer, 0)} to ${pp(C6.P2_pag_full.oer - C6.B0_naive.oer, 0)} points.`),
  body(`Contributions. (1) A component-level evaluation with explicit reference conditions, a three-stratum generator whose record-required stratum makes benign verdicts checkable, and the benign cost measured on the same alerts as the security effect. (2) The finding that, on this benchmark, provenance marking behaves like a shift of the operating point rather than an improvement in discrimination, that appendix relocation showed no advantage over inline labeling, and that the gate accepted no downgrade on either model. (3) A cross-model contrast in which attack success from this corpus was observed on one model and the cost on both. (4) A released artifact — generator, corpus, harness, per-item outputs, pilots, extended version: ${REPO}.`),
];

const related = [
  H1("Related Work"),
  body(`Perez and Ribeiro [2] introduced goal hijacking through adversarial text in the user turn; Greshake et al. [1] generalized to the indirect setting, where attacker-planted content in retrieved data compromises the application; Liu et al. [3] found 31 of 36 commercial applications vulnerable, and prompt injection heads the OWASP Top 10 for LLM Applications [4]. Defenses fall into three families. *Prompt-level* defenses mark untrusted content: Hines et al. [6] formalize this as spotlighting and report attack success falling from above 50% to below 2% on summarization and question-answering. *Training-level* defenses teach the model to rank channels: StruQ [7] fine-tunes on structured queries and the instruction hierarchy [8] improves in-domain robustness by up to 63% while reporting over-refusal regressions. *Architectural* defenses remove the ability to act on untrusted text by construction: CaMeL [9] separates a privileged planner from a quarantined model, solving 77% of AgentDojo tasks against 84% undefended. None reports its gain on security data, and none pairs a utility cost with the security effect on the same inputs. AgentDojo [5] finds no defense with both high utility and low attack success, and Wang et al. [10] show that many defenses look effective by suppressing contextual input and fail where context-dependent reasoning is essential — as in alert triage, where the attacker-writable fields are also where a benign alert explains itself.`, { noIndent: true }),
  body(`Ndichu et al. [13] list injection through log entries as an open direction the alert-screening literature has not evaluated; Alahmadi et al. [14] document the suppression heuristics analysts adopt under volume. Pandey and Bhujang [11] first evaluate log-borne injection systematically — a four-class taxonomy (S1 direct override, S2 persona hijack, S3 context manipulation, S4 obfuscated), four defense modes, three tasks, 200 synthetic logs per condition derived from CIC-IDS2017 [15] and UNSW-NB15 [16] schemas, on gpt-4o-mini — and find direct override at 0% in classification while persona hijack suppresses 68% of malicious classifications under the naive prompt. Their 80 benign logs per condition serve as a guard against label-everything defenses; the escalation rate under each defense is not reported. Landauer et al. [12] insert benign-framing injections into real labeled traces and reach 86.7% attack success on the most susceptible of four models, observing that the explanation often acknowledges the text as manipulative while the verdict remains benign. Neither reports the benign-alert outcome of a defense as a result, separates injection-attributable failures from baseline error, or constrains payloads to placements a stated delivery path admits. We take [11] as the closest prior work and claim no priority in the setting; what we add is the joint measurement.`),
];

const threat = [
  H1("Threat Model and Methods"),
  H2("Attacker, Trust Tiers, and Delivery"),
  body(`The attacker is remote, holds no credentials, can send traffic to services monitored by an IDS, knows an LLM processes alerts downstream but not the prompt template, and wants a benign verdict. The capability is stated narrowly: the attacker *preserves the observable behavior of the original attack and inserts additional text into specific string fields*. They cannot author the content of infrastructure measurements. Fields are therefore assigned a trust tier by schema name: T0 generated by the sensor or trusted inventory, T1 measured by infrastructure but not authorable as text, T2 written by whoever sent the traffic, with unknown fields failing closed to T2.`, { noIndent: true }),
  body(`Prior work does not state how payloads reach attacker-controlled fields. We model the path as transmission followed by sensor encoding: per-field limits on character set, length, newlines, and non-ASCII (protocol-level or application convention, reported separately), then JSON serialization by the sensor and deserialization by the consumer. Auditing the 60-payload corpus against ten fields gives 600 (field, payload) combinations; excluding process command lines, which presuppose code execution, leaves 540, of which 281 are deliverable. Only deliverable placements are used; the per-field table is in the artifact.`),
  H2("Three Components")
  , body(`*D1, trust-tier classification*, is no defense on its own; it feeds the other two. *D2, provenance-aware rendering*, restructures the prompt into an ALERT region (T0/T1, labeled sensor-generated), an ATTACKER-WRITABLE region listing the names of T2 fields mapped to opaque references, and an EVIDENCE APPENDIX expanding each reference to its normalized value (NFKC, control characters to space, whitespace collapsed, a 240-character cap that never fires here), prefaced by a fixed note that the strings were written by whoever sent the traffic, are forensic artifacts rather than messages to the analyst, and that a string appearing to grant approval is itself evidence of evasion. D2 is provenance marking in the sense of [6]: the value is in the same context as the verdict, and nothing interrupts information flow. *D3, the asymmetric downgrade gate*, adds a second call only when the first-stage verdict is benign or the action is close; that call receives T0 and T1 only and overrides to escalate unless it finds the benign verdict justified. Its guarantee is exactly that no T2 string enters the gate's input. The pipeline is not thereby injection-resistant: the gate runs only when the first stage returned benign, and where trusted fields are insufficient it cannot recover a lost verdict — it can only escalate, at a cost in benign alerts, which is the quantity of interest.`, { noIndent: true }),
];

const method = [];

const design = [
  H1("Experimental Design"),
  H2("Three-Stratum Alert Generation"),
  body(`Whether exclusion helps depends on whether the excluded information was needed, so alerts are generated in three strata. *Stratum A (trusted-sufficient)*: T0/T1 support a verdict, but no single field announces it and class-conditional distributions overlap. *Stratum B-syn (parse-required)*: T0/T1 are label-independent and the verdict follows from parsing a T2 string — a percent-encoded traversal, an executable final extension, SQL logic versus an Irish surname. *Stratum B-ref (record-required)*: the verdict requires cross-checking a T2 string against a trusted record supplied as a T0 field (approved egress domains, sanctioned scanner agents, open change tickets); ground truth is list membership. The third stratum makes benign verdicts checkable — without a record, a benign verdict reached by finding a fabricated identifier plausible is indistinguishable from one reached by verification — and it is where the gate, seeing the list but not the string, cannot complete the check. Five signature families appear in both classes, so no signature is class-determining.`, { noIndent: true }),
  body(`Appending a payload can change the task rather than attack it (a filename's extension, a hostname), so an executable oracle encoding each template's decisive property must return the same label before and after injection; placements that would change it are rejected. Two non-LLM baselines bound difficulty: R0 applies a three-line rule over T0/T1 and never reads T2, so it is injection-immune by construction; R1 parses T2. R1 implements essentially the checks the oracle encodes and performs near ceiling on the B strata by construction; both are difficulty bounds, not evidence for or against LLM triage.`),
  H2("Conditions"),
  body(`Each condition is defined by what it adds to a stated reference condition: B0, the naive prompt; B1 = B0 + field tags and an untrusted-content warning; B1N = B1 + normalization; B2 = B1 + keyword filter; B3 = B1 + a JSON-only reminder and forged-verdict warning; P0 = B1N + trust tiers and the provenance note (D1, D2 inline); P1 = P0 + the referenced appendix (D2); P2 = P1 + the downgrade gate (D3); and the non-LLM R0 and R1. B2 and B3 branch from B1 rather than succeeding each other. B1 is the primary baseline, the strongest classification mode in [11]; B3 approximates that work's structured-plus-templated mode; since our harness requires JSON from every condition, B3 adds a JSON-only reminder and a forged-verdict warning, and B3 versus B1 estimates templating plus that warning. P1 differs from P0 in more than position (reference identifiers, a second occurrence of each field name), so P1 versus P0 isolates referenced-appendix rendering as a bundle.`, { noIndent: true }),
  spacer(20),
  H2("Metrics and Statistics"),
  body(`A verdict on a malicious alert *fails* if it is benign or recommends closing; a benign alert is *over-escalated* under the complementary rule, when the verdict is not benign and the action is not close (a monitor action with a suspicious verdict counts as escalation). Each malicious alert is judged with and without its payload, giving transition cells cc (correct in both), cf (correct clean, failed injected: the injection-attributable failure), fc, and ff; per-condition cells are in the artifact. The *injected miss rate* — injected malicious alerts finally missed, over the full malicious sample, so its denominator is identical across conditions — and the *over-escalation rate* (OER) on benign alerts, a false-positive rate on benign input, are the pre-specified co-primary pair. Alongside them we report attack-free quantities: TPR, FPR (= OER), Youden's J = TPR − FPR with a 95% interval by Newcombe's hybrid score method [20], and balanced accuracy. J summarizes quality at the operating point each condition chose without separating a moved threshold from a changed ranking. The conditional attack success rate cf/(cc + cf), whose denominator varies by condition, is not used for ranking.`, { noIndent: true }),
  body(`Every alert is evaluated under every condition, so comparisons are paired: exact McNemar tests [19] on discordant pairs, OER with Wilson intervals [18]. Six comparisons are pre-specified and Holm-corrected — P1 vs P0, P0 vs B1N, B1N vs B1, P1 vs B1, and P2 vs P1 on injected misses, and P2 vs P1 on OER *within the record-required stratum*, where the excluded information was needed. All other analyses are exploratory. Non-significance does not establish equivalence; we report that an advantage was not demonstrated, not that it is absent.`),
  H2("Judge Protocol and Post Hoc Conditions"),
  body(`Every judgment is an independent stateless call with a fixed system prompt; no two alerts share a context window. This requirement, and class-ambiguous signatures, come from pilot studies reported in the extended version. Responses are constrained to JSON (unparseable output scores as escalate) and cached by content hash. gpt-4o-mini ran at temperature 0 with a fixed seed; gpt-6-astra rejected both parameters and ran under provider-default sampling, so the models differ in decoding as well as weights. Conditions rendering byte-identical prompts share one cached response (B1N equals B1 on 258 of 288 items, B2 equals B1 on 273, P2's first stage equals P1 on all, so P2 versus P1 isolates the gate exactly).`, { noIndent: true }),
  body(`After the main results were known we ran four exploratory conditions on both models, outside the pre-specified family: L0 and L1, which truncate P1's provenance note to its provenance statement alone and to that plus an authority-denial clause; N, which keeps P1's layout and authority clause but labels the fields SENDER-SUPPLIED and says their content may be evidence for or against the alert; and G, the downgrade gate applied to every alert as a standalone classifier.`),
];

const pilot = [];

const results = [
  H1("Results"),
  body(`Each model runs N = 60 alerts per generator seed over three seeds, which fix the alerts, the payload drawn for each malicious alert (category by rotation, string uniformly from the 15 in that category), and its field; the same seed value is passed as the sampling seed on gpt-4o-mini. This gives 108 malicious and 72 benign alerts per condition, 288 judgments including both variants of malicious alerts. Every response parsed as JSON. Table I reports the co-primary pair and the attack-free quantities; Fig. 1 plots both.`, { noIndent: true }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 }, keepNext: true,
    children: [new ImageRun({ data: fs.readFileSync(path.join(__dirname, "fig1_safety_cost_conf.png")), transformation: { width: 244, height: 438 }, type: "png" })] }),
  caption("Fig. 1. ", "Both models, the eight pre-specified conditions, R0/R1, and the post hoc N and G (L0, L1 omitted), three seeds pooled. (a) The pre-specified operational pair; lower left is better. (b) Attack-free discrimination with the chance diagonal (J = 0). P2 and G coincide at the escalate-everything corner on both models; on gpt-4o-mini P0 and P1 lie near the diagonal while N sits with the baselines."),
  spacer(60),
  H2("Primary Comparison"),
  body(`On gpt-4o-mini the ordering on injected misses runs from the unprotected baseline (${pc(C4.B0_naive.injected_miss)}%) through the structured baselines (${rng(C4, 'injected_miss', SB)}%) to the provenance conditions (${pc(C4.P0_inline_prov.injected_miss)}% and ${pc(C4.P1_pag_render.injected_miss)}%) and the gate (${pc(C4.P2_pag_full.injected_miss)}%). Over-escalation runs the same way: ${pc(C4.B0_naive.oer)}%, ${rng(C4, 'oer', SB)}%, ${pc(C4.P1_pag_render.oer)}–${pc(C4.P0_inline_prov.oer)}%, ${pc(C4.P2_pag_full.oer)}%. Relative to B1, P0 and P1 lower misses and raise OER; P2 lowers misses further and raises OER further. Attack-free J declines from ${pp(C4.B0_naive.youden_j)} at B0 to ${pp(C4.P0_inline_prov.youden_j)} at P0 and ${pp(C4.P1_pag_render.youden_j)} at P1, both with intervals including zero; P2 escalated all 288 judgments and has J = 0 (${jci(C4.P2_pag_full)}).`, { noIndent: true }),
  body(`On gpt-6-astra no LLM condition missed any malicious alert, injected or clean, so the comparison rests on cost. Over-escalation rises from ${pc(C6.B0_naive.oer)}% at B0 to ${rng(C6, 'oer', SB)}% for the structured baselines, ${pc(C6.P1_pag_render.oer)}% and ${pc(C6.P0_inline_prov.oer)}% for the provenance conditions, and ${pc(C6.P2_pag_full.oer)}% for the gate; J falls from ${pp(C6.B0_naive.youden_j)} to ${pp(C6.P1_pag_render.youden_j)}, ${pp(C6.P0_inline_prov.youden_j)}, and 0. The parser R1 has the highest attack-free J on both models (${pp(C4.R1_rule_t2parser.youden_j)}), a property of the benchmark's construction (Section IV-A).`),
  spacer(40),
  caption("TABLE I. ", "Primary comparison, three seeds pooled (108 malicious, 72 benign per condition). OER with Wilson 95% interval. TPR, J, and BA are attack-free; J = TPR − FPR with a Newcombe 95% interval [20]. R0 and R1 are deterministic and identical across models. N is the post hoc neutral rewording (Section V-E).", { keepNext: true }),
  tbl(["Cond.", "Inj. miss", "OER [95% CI]", "TPR", "J [95% CI]", "BA"],
    ["B0_naive", "B1_structured", "B1N_structured_norm", "B2_sanitized", "B3_constrained",
     "P0_inline_prov", "P1_pag_render", "P2_pag_full", "R0_rule_t01", "R1_rule_t2parser", "N"].map(c => {
      const t = c === "N" ? FN4 : C4[c];
      return [c === "N" ? "N" : c.split("_")[0], pc(t.injected_miss), `${pc(t.oer)} ${ci(t.oer_ci)}`, pc(t.tpr), `${pp(t.youden_j)} ${jci(t)}`, pc(t.balanced_acc)];
    }), [560, 640, 1240, 540, 1340, 540]),
  caption("", "(a) gpt-4o-mini, temperature 0."),
  spacer(30),
  tbl(["Cond.", "Inj. miss", "OER [95% CI]", "TPR", "J [95% CI]", "BA"],
    ["B0_naive", "B1_structured", "B1N_structured_norm", "B2_sanitized", "B3_constrained",
     "P0_inline_prov", "P1_pag_render", "P2_pag_full", "N"].map(c => {
      const t = c === "N" ? FN6 : C6[c];
      return [c === "N" ? "N" : c.split("_")[0], pc(t.injected_miss), `${pc(t.oer)} ${ci(t.oer_ci)}`, pc(t.tpr), `${pp(t.youden_j)} ${jci(t)}`, pc(t.balanced_acc)];
    }), [560, 640, 1240, 540, 1340, 540]),
  caption("", "(b) gpt-6-astra, provider-default sampling."),
  spacer(60),
  H2("Pre-Specified Comparisons"),
  body(`Table II reports the six pre-specified comparisons. On gpt-4o-mini three reach significance, all comparisons in which the more escalation-prone condition wins on malicious alerts: P0 vs B1N (${bc(M4.prespecified[1])} discordant), P1 vs B1 (${bc(M4.prespecified[3])}), and P2 vs P1 (${bc(M4.prespecified[4])}). Read against Table I, each is what a condition that escalates more of everything must produce; the test is valid but the quantity tested is not discrimination. The two comparisons that isolate the proposed mechanisms do not reach significance. Appendix relocation over inline labeling (P1 vs P0) gives ${bc(M4.prespecified[0])}, ${peq(M4.prespecified[0].p)}: the conditions split their ${nm(M4.prespecified[0].a_only + M4.prespecified[0].b_only)} disagreements nearly evenly. Normalization (B1N vs B1) gives ${bc(M4.prespecified[2])}, the ceiling for prompts that coincide on 258 of 288 items. The stratified comparison — the gate's OER cost within the record-required stratum — gives ${bc(M4.prespecified[5])}, all discordant pairs in the direction of the gate escalating more, ${peq(M4.prespecified[5].p)}; the direction is the one the design predicted, the sample does not establish it. On gpt-6-astra every comparison has zero discordant pairs.`, { noIndent: true }),
  spacer(40),
  caption("TABLE II. ", "Pre-specified comparisons, gpt-4o-mini: exact McNemar on discordant pairs (b = first condition only fails, c = second only fails), Holm-corrected over the family of six. gpt-6-astra: b = c = 0 throughout.", { keepNext: true }),
  tbl(["Comparison", "Label", "b/c", "p", "p_Holm", "Sig."],
    M4.prespecified.map(r => [
      `${r.a.split("_")[0]} vs ${r.b.split("_")[0]}${r.stratum ? " (" + r.stratum + ")" : ""}`,
      r.label === "malicious" ? "mal." : "ben.",
      bc(r), pv(r.p), pv(r.p_holm), r.significant ? "yes" : "no"]),
    [1400, 580, 600, 720, 720, 540]),
  spacer(60),
  H2("Gate Behavior"),
  body(`The gate was invoked whenever P1's first stage proposed closing an alert: ${nm(M4.gate.fired)} times on gpt-4o-mini and ${nm(M6.gate.fired)} on gpt-6-astra, and it rejected the downgrade in all ${nm(M4.gate.fired + M6.gate.fired)} cases. On the small model ${nm(M4.gate.malicious_seen)} invocations were evaluations of malicious alerts P1 had proposed to close (${nm(C4.P1_pag_render.cf + C4.P1_pag_render.ff)} injected-variant misses, ${nm(C4.P1_pag_render.cf)} of them injection-attributable, and ${nm(C4.P1_pag_render.fc + C4.P1_pag_render.ff)} clean-variant misses), and rejecting them was correct — no injection-induced miss survived; the other ${nm(M4.gate.benign_seen)} were benign alerts from the record-required stratum, where the gate cannot see the string it would need. On the frontier model all ${nm(M6.gate.fired)} invocations were benign and every rejection a cost. Because that subset is selected by the first stage, we ran the gate on every alert (condition G): on both models it accepted a downgrade for none of 288 judgments, including all ${nm(F4.gate_alone_benign.total.n)} benign alerts, while R0, reading the same sensor fields, closes ${nm(F4.gate_alone_benign.total.r0_closed)} of them. R0 also misses ${pc(M4.by_stratum.R0_rule_t01.A.injected_miss, 0)}% of malicious alerts in the trusted-sufficient stratum, so this does not show the trusted fields justified a *safe* close; it shows that first-stage selection is not the explanation, and that under the one gate configuration we tested the verifier never verified, on either model.`, { noIndent: true }),
  H2("Frontier Model"),
  body(`Across eight conditions and 108 malicious alerts each, no injected verdict on gpt-6-astra differed from its clean counterpart; the Wilson upper bound on a zero count of 108 is ${pc(RES.wilson_upper_0_of_108)}% per condition. Three accounts fit: robustness to the corpus; an escalation prior strong enough that no payload overcomes it, which the ${pc(C6.B0_naive.oer)}% over-escalation of the unprotected baseline makes plausible; or a corpus, validated against the small model, that is weak against this one. Every malicious alert was a correct verdict the payload could have broken (cc = 108, cf = 0 in every condition). What the frontier data do show is that the cost side is unchanged: the same prompt changes raise over-escalation from ${pc(C6.B0_naive.oer)}% to ${pc(C6.P1_pag_render.oer)}% for the rendering and ${pc(C6.P2_pag_full.oer)}% for the gate, with no security benefit to offset it. Size, training, safety tuning, and decoding differ jointly, so we do not attribute the difference to capability.`, { noIndent: true }),
  H2("Post Hoc Decomposition of the Provenance Note"),
  body(`Is the over-escalation a property of provenance marking or of one alarming sentence? On gpt-4o-mini both contribute: OER rises with each clause added. L0, which gives no instruction but still labels the fields ATTACKER-WRITABLE, escalates ${pc(W4.levels.X1_note_minimal.oer)}% of benign alerts against ${pc(C4.B1_structured.oer)}% for B1, bounding the cost of the label-and-layout bundle. The authority clause raises OER to ${pc(W4.levels.X2_note_authority.oer)}% (${bc(W4.benign[0])} discordant, ${peq(W4.benign[0].p)}) and the severity clause to ${pc(W4.levels.P1_pag_render.oer)}% (${bc(W4.benign[1])}, ${peq(W4.benign[1].p)}; Holm ${pv(W4.benign[1].p_holm)} within the family of two ladder comparisons — all other p-values in this subsection are uncorrected), and each lowers misses (${bc(W4.malicious[0])} and ${bc(W4.malicious[1])}). J falls from ${pp(W4.levels.X1_note_minimal.youden_j)} to ${pp(W4.levels.X2_note_authority.youden_j)} to ${pp(W4.levels.P1_pag_render.youden_j)}. The neutral condition N (Table I) locates most of the effect: against L1, with the same authority clause, N escalates ${nm(fpair(F4, "X2_note_authority", "X3_note_neutral").benign.a_only)} fewer benign alerts and none more (${peq(fpair(F4, "X2_note_authority", "X3_note_neutral").benign.p)}) and misses ${nm(fpair(F4, "X2_note_authority", "X3_note_neutral").malicious.b_only)} more malicious ones (${peq(fpair(F4, "X2_note_authority", "X3_note_neutral").malicious.p)}). Against B1 no difference was detected on either axis (benign ${bc(fpair(F4, "X3_note_neutral", "B1_structured").benign)}, ${peq(fpair(F4, "X3_note_neutral", "B1_structured").benign.p)}; malicious ${bc(fpair(F4, "X3_note_neutral", "B1_structured").malicious)}, ${peq(fpair(F4, "X3_note_neutral", "B1_structured").malicious.p)}), and N has the highest attack-free J of any LLM condition; absent an equivalence test this is a failure to detect a difference, not a demonstration of none.`, { noIndent: true }),
  body(`On gpt-6-astra no differences among the wordings were detected: L0 ${pc(W6.levels.X1_note_minimal.oer)}%, L1 ${pc(W6.levels.X2_note_authority.oer)}%, L2 (P1) ${pc(W6.levels.P1_pag_render.oer)}%, and N ${pc(FN6.oer)}% OER, and no comparison among them reaches significance. But N against B1 is not the undetected difference it was on the small model: ${bc(fpair(F6, "X3_note_neutral", "B1_structured").benign)} discordant, ${peq(fpair(F6, "X3_note_neutral", "B1_structured").benign.p)}, with N escalating more. N differs from B1 in tiers, relocation, note, authority clause, and normalization at once, so the residual ${pp(FN6.oer - C6.B1_structured.oer, 0)} points is not attributed to any one of them. The rewording lowered the cost substantially on the small model and not detectably on the frontier model.`),
];

const discussion = [
  H1("Discussion"),
  body(`*Operating point versus discrimination.* On this benchmark the security metric and the cost metric did not move independently. On gpt-4o-mini, relative to B1, both P0 and P1 reduced injected misses while increasing OER; adding the gate to P1 further reduced misses and increased OER; and each clause added to the provenance note did the same. The simplest account of a classifier whose true- and false-positive rates rise together toward the corner is a moved threshold with an unchanged ranking; the observation is consistent with that account but does not establish it, since each condition yields one binary verdict per alert. A study measuring only attack success would conclude that provenance rendering reduced the injected miss rate by ${relred(C4.B1_structured.injected_miss, C4.P1_pag_render.injected_miss)}% relative to B1 (${nm(C4.B1_structured.injected_miss * 108)} to ${nm(C4.P1_pag_render.injected_miss * 108)} of 108) and a gate eliminated it; both are true of our data, and neither describes a usable system.`, { noIndent: true }),
  body(`*What the two mechanisms did.* Appendix relocation was hypothesized to make authority claims self-undermining; P1 and P0 split their ${nm(M4.prespecified[0].a_only + M4.prespecified[0].b_only)} disagreements nearly evenly, so no benefit of the referenced appendix beyond inline provenance rendering was detected. The gate, the only component with an information-flow guarantee, honored it at the price of a verifier that never verified: under P2 and under G, on two models, it accepted no downgrade while a three-line rule on the same fields closed most benign alerts. *Attack success differed between models; increased OER was observed on both.* Sixty payloads that broke ${pc(C4.B0_naive.asr_cond, 0)}% of the small model's correct verdicts under B0 (${nm(C4.B0_naive.cf)} of ${nm(C4.B0_naive.asr_denom)}) broke none of the frontier model's, and our data do not separate robustness from a conservative prior or a weak corpus; but on both models the same prompts raised over-escalation, on the model where this corpus produced no attack success as well as on the one where it did.`),
];

const limits = [
  H1("Limitations and Future Work"),
  body(`*Synthetic alerts.* Alerts are generated from schemas, and the high over-escalation of even the unprotected baseline on the frontier model suggests they look more suspicious than production alerts; validation on the AIT Alert Data Set [17] is the next step. *Task difficulty.* Both B strata are resolvable by a parser; future benchmarks need alerts an LLM resolves and a parser cannot, where the gate's cost would also be measured fairly. *The frontier null.* Separating robustness from a conservative prior or a weak corpus needs borderline benign alerts, an adaptive attacker — most obviously a minimal-claim payload that reads as an ordinary field value — and elicited scores for operating-point comparison. *Decoding and consumption path.* Cross-model differences confound weights with decoding; only the parse path was run. *Prompt identity.* Normalization and filtering change the prompt on only 30 and 15 of 288 items, so B1N vs B1 and B2 vs B1 need an obfuscation-weighted corpus. *Post hoc conditions* are exploratory, no equivalence test supports a claim of zero effect, and the frontier model's residual cost under N was not decomposed; an inline neutral rendering would separate tiers from relocation. *One gate prompt.* A less conservative gate, or one invoked on a trusted-signal threshold, is untested; comparing gate prompts would locate the refusal in the prompt or the task. *Prompt tuning, output format, single turn.* Baseline prompts follow [11] as closely as its description allows while the proposed conditions were iterated during piloting; every condition emits JSON; and the model classifies one alert per call, with no agent state.`, { noIndent: true }),
];

const conclusion = [
  H1("Conclusion"),
  body(`Attackers write much of the text that security tooling reads. We examined two responses — marking provenance in the prompt, which does not interrupt information flow, and excluding untrusted input from a verification stage — in an evaluation that attributes effects to components and measures the cost on benign traffic as a co-primary quantity. On the small model the marking reduced injected misses from ${pc(C4.B1_structured.injected_miss)}% to ${pc(C4.P1_pag_render.injected_miss)}% and raised over-escalation from ${pc(C4.B1_structured.oer)}% to ${pc(C4.P1_pag_render.oer)}% relative to the structured baseline; the exclusion reached zero misses by refusing every downgrade; no advantage of appendix relocation was demonstrated; and a neutral rewording lowered both cost and benefit to levels not distinguishable from that baseline. On a frontier model the corpus flipped no verdict, the prompts still cost, and the rewording left the cost above the baseline. The pattern is consistent with a moved operating point rather than improved discrimination, and the cost appeared on both models. We release everything needed to re-ask the question as models change.`, { noIndent: true }),
];

// IEEE requires AI-generated content to be disclosed in the acknowledgments,
// naming the system, the sections, and the level of use.
const ack = [
  new Paragraph({ alignment: AlignmentType.CENTER, keepNext: true, spacing: { before: 200, after: 80 },
    children: [R("ACKNOWLEDGMENT", { size: 20 })] }),
  body(`*Use of generative AI.* Claude (Anthropic) was used to draft and revise the text of all sections; to develop and debug the code for alert generation, experimental execution, statistical analysis, and plotting; and to generate the 60 injection payload strings following the taxonomy in [11]. ChatGPT (OpenAI) was used to provide feedback on manuscript structure, statistical interpretation, consistency between results and claims, and wording. The authors reviewed and revised all AI-assisted material, regenerated every reported figure from the per-item records with the released scripts, and take responsibility for the final manuscript, code, analyses, and conclusions.`, { noIndent: true }),
];

const refs = [
  "K. Greshake et al., “Not what you’ve signed up for: Compromising real-world LLM-integrated applications with indirect prompt injection,” in Proc. 16th ACM Workshop Artif. Intell. Secur. (AISec), 2023, pp. 79–90.",
  "F. Perez and I. Ribeiro, “Ignore previous prompt: Attack techniques for language models,” in NeurIPS ML Safety Workshop, 2022, arXiv:2211.09527.",
  "Y. Liu et al., “Prompt injection attack against LLM-integrated applications,” arXiv preprint arXiv:2306.05499, 2023.",
  "OWASP Foundation, “OWASP Top 10 for LLM Applications 2025,” Nov. 2024, owasp.org.",
  "E. Debenedetti et al., “AgentDojo: A dynamic environment to evaluate prompt injection attacks and defenses for LLM agents,” in Proc. NeurIPS Datasets and Benchmarks Track, 2024.",
  "K. Hines et al., “Defending against indirect prompt injection attacks with spotlighting,” arXiv preprint arXiv:2403.14720, 2024.",
  "S. Chen, J. Piet, C. Sitawarin, and D. Wagner, “StruQ: Defending against prompt injection with structured queries,” in Proc. 34th USENIX Security Symp., 2025.",
  "E. Wallace et al., “The instruction hierarchy: Training LLMs to prioritize privileged instructions,” arXiv preprint arXiv:2404.13208, 2024.",
  "E. Debenedetti et al., “Defeating prompt injections by design,” arXiv preprint arXiv:2503.18813, 2025.",
  "P. Wang et al., “The landscape of prompt injection threats in LLM agents: From taxonomy to analysis,” arXiv preprint arXiv:2602.10453, Feb. 2026.",
  "R. Pandey and A. Bhujang, “Poisoning the watchtower: Prompt injection attacks against LLM-augmented security operations through adversarial log content,” arXiv preprint arXiv:2605.24421, May 2026.",
  "M. Landauer, F. Skopik, M. Wurzenberger, F. Górski, and M. Krzysztoń, “Just testing, move along: Evasion of LLM-based system log interpretation by prompt injection,” arXiv preprint arXiv:2607.24174, Jul. 2026.",
  "S. Ndichu, T. Ban, S. Ozawa, T. Takahashi, and D. Inoue, “AI-driven security alert screening and alert fatigue mitigation in security operations centers: A survey,” arXiv preprint arXiv:2605.08316v2, 2026.",
  "B. A. Alahmadi, L. Axon, and I. Martinovic, “99% false positives: A qualitative study of SOC analysts’ perspectives on security alarms,” in Proc. 31st USENIX Security Symp., 2022, pp. 2783–2800.",
  "I. Sharafaldin, A. H. Lashkari, and A. A. Ghorbani, “Toward generating a new intrusion detection dataset and intrusion traffic characterization,” in Proc. ICISSP, 2018, pp. 108–116.",
  "N. Moustafa and J. Slay, “UNSW-NB15: A comprehensive data set for network intrusion detection systems (UNSW-NB15 network data set),” in Proc. MilCIS, 2015, pp. 1–6.",
  "M. Landauer, F. Skopik, and M. Wurzenberger, “Introducing a new alert data set for multi-step attack analysis,” in Proc. 17th Cyber Security Experimentation and Test Workshop (CSET), 2024.",
  "E. B. Wilson, “Probable inference, the law of succession, and statistical inference,” J. Amer. Statist. Assoc., vol. 22, no. 158, pp. 209–212, 1927.",
  "Q. McNemar, “Note on the sampling error of the difference between correlated proportions or percentages,” Psychometrika, vol. 12, no. 2, pp. 153–157, 1947.",
  "R. G. Newcombe, “Interval estimation for the difference between independent proportions: Comparison of eleven methods,” Statist. Med., vol. 17, no. 8, pp. 873–890, 1998.",
];

const appendix = [];
